
@startuml
autonumber
actor me
me -> Observable : map(mapFun)
Observable -> OnSubscribeMap : new OnSubscribeMap(this,mapFun)
OnSubscribeMap --> Observable : onSubscribeMap
Observable -> Observable : create(onSubscribeMap)
me -> Observable : subscribe(...)
Observable -> OnSubscribeMap : call(subscriber)
OnSubscribeMap -> MapSubscriber : new MapSubscriber(subscriber,mapFun)
OnSubscribeMap -> Subscriber : add(mapSubscriber)
OnSubscribeMap -> Observable : unsafeSubscribe(mapSubscriber)
Observable -> MapSubscriber : onStart()
OnSubscribe -> MapSubscriber : onNext(T)
MapSubscriber -> MapSubscriber : mapFun.call(T)
MapSubscriber -> Subscriber : onNext(R)
OnSubscribe -> MapSubscriber : onCompleted()/onError(e)
MapSubscriber -> Subscriber : onCompleted()/onError(e)


@enduml