
@startuml
autonumber
actor me
me -> sourceObservable : map(mapFun)
sourceObservable -> onSubscribeMap : new OnSubscribeMap(this,mapFun)
sourceObservable -> mapObservable : create(onSubscribeMap)
me -> mapObservable : subscribe(targetSubscriber)
mapObservable -> targetSubscriber : onStart()
mapObservable -> onSubscribeMap : call(targetSubscriber)
onSubscribeMap -> mapSubscriber : new MapSubscriber(targetSubscriber,mapFun)
onSubscribeMap -> targetSubscriber : add(mapSubscriber)
onSubscribeMap -> sourceObservable : unsafeSubscribe(mapSubscriber)
sourceObservable -> mapSubscriber : onStart()
sourceObservable -> sourceOnSubscribe : call(mapSubscriber)
sourceOnSubscribe -> sourceOnSubscribe : do work
sourceOnSubscribe -> mapSubscriber : onNext(T)
mapSubscriber -> mapFun : call(T)
mapSubscriber -> targetSubscriber : onNext(R)
sourceOnSubscribe -> mapSubscriber : onCompleted()/onError(e)
mapSubscriber -> targetSubscriber : onCompleted()/onError(e)


@enduml