
@startuml
autonumber
actor me
me -> sourceOnSubscribe : new OnSubscribe(...)
me -> Observable : create(sourceOnSubscribe)
Observable -> sourceObservable : new Observable(sourceOnSubscribe)
me -> targetSubscriber : new Subscriber(...)
me -> sourceObservable : subscribe(targetSubscriber)
sourceObservable -> targetSubscriber : onStart()
sourceObservable -> sourceOnSubscribe : call(targetSubscriber)
sourceOnSubscribe -> sourceOnSubscribe : do work
sourceOnSubscribe -> targetSubscriber : onNext(T)
sourceOnSubscribe -> targetSubscriber : onCompleted()/onError(e)

@enduml